### ISSUE TITLE
How to remove the Bouncing Effect?

### ISSUE THREAD

**Issue by NuelNikhil** [jackalcooper/DragSlideView#2]
Hello @jackalcooper How Can I remove that bouncing effect from Nib file ? I have been using your project and I need some Customisations in it and one is this. :)

**Comment by jackalcooper** [comment]
Buncing effect comes from UIDynamic not Nib. Try to remove the code you don't want in DragSlideView/SettingsView.swift. Hope this helps you.

**Comment by NuelNikhil** [comment]
@jackalcooper  I tried commenting  `animator.removeBehavior(snap)` inside **panGestureEnded** Method and Now there is no bouncing effect... 👍

**Comment by NuelNikhil** [comment]
@jackalcooper  One more question Currently the nib file is positioned at the bottom of the screen. How Can i make it at the top for the first the the page loads ?

**Comment by jackalcooper** [comment]
Check out ViewController.swift. It is initialized in this file.

**Comment by NuelNikhil** [comment]
Yup I did it like that too. I have this code  ```
notifications = NSBundle.mainBundle().loadNibNamed("Notifications", owner: self, options: nil).last as? NotificationsView
        notifications.frame = CGRectMake(0, -self.view.frame.size.height + 70, self.view.frame.size.width, self.view.frame.size.height)
        self.view.addSubview(notifications)
        notifications.setup()
```
in one of my viewcontroller but then file shows at the bottom, is there anything to do with nib file (Corresponding swift file) ?

**Comment by jackalcooper** [comment]
Sorry no idea about what you said

**Comment by NuelNikhil** [comment]
I tried to change the y value inside viewcontroller.swift in this line        ` settings.frame = CGRectMake(0, -self.view.frame.size.height + 180, self.view.frame.size.width, self.view.frame.size.height)` 

but I didn't find any changes. I need the nib file to be positioned in such way that it should be appeared some points from top i.e.: what we see when we get after after swiping nib file from bottom to top.

**Comment by jackalcooper** [comment]
Well I can only explain it this way but I'm not sure if it's right
: The original position has nothing to do with the boundaries of the UIDynamic "Field".
